spring.application.name=trabalho-desweb
api.security.token.secret=7tfFRx6R1B-nkzXBiTibPh9MnQAS5sDnDaHrPgeL04a-4NBfPU7xHqPyAQ8-W5-a-RdCI_Zlz7WF8I0OR37TsA
jwt.security.accessTokenExpiration=7200

spring.datasource.url=jdbc:mysql://localhost:3306/trabalho_desweb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Brigadeiro1612!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest